### ISSUE TITLE
Provisioning/Deployment/Circle

### ISSUE THREAD

**Issue by awsmsrc** [speak/account#10]

**Comment by willbarrett** [comment]
Will this live on the same domain as the website, perhaps at a sub-path, or will it get its own subdomain?
Will this be purely static (S3 deployment), or will there be a dynamic aspect to it?

**Comment by awsmsrc** [comment]
account.speak.io

should be purely s3, this issue is as much for discussion as anything else

**Comment by willbarrett** [comment]
If @tommoor is good with that theory, I can move forward with this. Better to get it done in advance if possible.

**Comment by tommoor** [comment]
I am, own subdomain at `account.`works a treat and it'll be totally static with a grunt build on CI.

**Comment by willbarrett** [comment]
Right on. I'll get this going soon then.

Will Barrett
Software Engineer
http://speak.io
@willbarrettdev

**Comment by willbarrett** [comment]
This should be done.
