### ISSUE TITLE
Custom organization selector

### ISSUE THREAD

**Issue by tommoor** [speak/account#17]
Show organization logo, custom styling for selector as mocked

**Comment by willbarrett** [comment]
Where are the mocks for this?

**Comment by ericbieller** [comment]
Hadn't designed this one yet, was thinking something simple like this:

![image](https://cloud.githubusercontent.com/assets/740552/10921132/7582bf00-8239-11e5-90b6-9163f99ee74a.png)

**Comment by willbarrett** [comment]
OK, cool. So, basically an accordion menu?
